package health

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

func writeRoot(t *testing.T, contents string) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".devloop"), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	path := filepath.Join(root, File)
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	return root
}

func TestLoad_MissingFile(t *testing.T) {
	root := t.TempDir() // no .devloop/provider-health.sh
	got := Load(root)
	if !got.SourceMissing {
		t.Errorf("expected SourceMissing=true on missing file, got %#v", got)
	}
	if got.Main.Limited() || got.Worker.Limited() {
		t.Errorf("expected neither side limited on missing file, got %#v", got)
	}
}

func TestLoad_Empty(t *testing.T) {
	root := writeRoot(t, "")
	got := Load(root)
	if got.SourceMissing {
		t.Errorf("file exists but parser reports SourceMissing=true")
	}
	if got.Main.Limited() || got.Worker.Limited() {
		t.Errorf("expected neither side limited on empty file, got %#v", got)
	}
}

func TestLoad_MainLimited(t *testing.T) {
	root := writeRoot(t, `
# generated by devloop
HEALTH_MAIN_LIMITED_SINCE=1716020118
HEALTH_MAIN_OVERRIDE=copilot
HEALTH_MAIN_LAST_PROBE=1716020700
HEALTH_WORKER_LIMITED_SINCE=
HEALTH_WORKER_OVERRIDE=
HEALTH_WORKER_LAST_PROBE=
`)
	got := Load(root)
	if !got.Main.Limited() {
		t.Errorf("expected main limited, got %#v", got.Main)
	}
	if got.Worker.Limited() {
		t.Errorf("expected worker healthy, got %#v", got.Worker)
	}
	if got.Main.Override != "copilot" {
		t.Errorf("override: want copilot, got %q", got.Main.Override)
	}
	want := time.Unix(1716020118, 0)
	if !got.Main.LimitedSince.Equal(want) {
		t.Errorf("LimitedSince: want %v, got %v", want, got.Main.LimitedSince)
	}
}

func TestLoad_HandlesQuotesAndExport(t *testing.T) {
	root := writeRoot(t, `
export HEALTH_MAIN_OVERRIDE="copilot"
HEALTH_WORKER_OVERRIDE='opencode'
`)
	got := Load(root)
	if got.Main.Override != "copilot" {
		t.Errorf("Main.Override: want copilot, got %q", got.Main.Override)
	}
	if got.Worker.Override != "opencode" {
		t.Errorf("Worker.Override: want opencode, got %q", got.Worker.Override)
	}
}

func TestLoad_TolerantOfGarbage(t *testing.T) {
	root := writeRoot(t, `
this is not a key=value line
HEALTH_MAIN_LIMITED_SINCE=not-a-number
=missing-key
HEALTH_WORKER_OVERRIDE=pi
   # comment with leading space
`)
	got := Load(root)
	// Bad number → zero time, not panic
	if !got.Main.LimitedSince.IsZero() {
		t.Errorf("expected zero time on non-numeric, got %v", got.Main.LimitedSince)
	}
	// Valid value still picked up
	if got.Worker.Override != "pi" {
		t.Errorf("Worker.Override: want pi, got %q", got.Worker.Override)
	}
}
