# DevLoop provider health state — auto-managed, do not edit manually
HEALTH_MAIN_LIMITED_SINCE=""
HEALTH_MAIN_OVERRIDE=""
HEALTH_MAIN_LAST_PROBE=""
HEALTH_WORKER_LIMITED_SINCE=""
HEALTH_WORKER_OVERRIDE=""
HEALTH_WORKER_LAST_PROBE=""
